home/urls.py
from django.urls import path

from django.views.generic import TemplateView
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.ArticleListView.as_view(), name='index'),
    path('category/', views.category_all, name='category_all'),
    path('category/<str:category>/', views.CategoryListView.as_view(), name='category_page'),
    path('tag/<str:tag>/', views.TagListView.as_view(), name='tag_page'),
    path('about/', TemplateView.as_view(template_name='home/about.html'), name='about'),
    path('contact/', TemplateView.as_view(template_name='home/contact.html'), name='contact'),
    path('support/', TemplateView.as_view(template_name='home/support.html'), name='support'),
    path('credits/', TemplateView.as_view(template_name='home/credits.html'), name='credits'),
    path('faqs/', views.FaqListView.as_view(), name='faqs'),
    path('privacy-policy/', TemplateView.as_view(template_name='home/privacy-policy.html'), name='privacy_policy'),
    path('terms/', TemplateView.as_view(template_name='home/terms.html'), name='terms'),
]

article/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCount, HitCountMixin

from django.template.defaultfilters import slugify
from django.utils.crypto import get_random_string
from django.urls import reverse

from datetime import datetime
import os, uuid

from .validators import validate_file_size

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        return super(Category, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Categories'



class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        return super(Tag, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Tags'



class Article(models.Model, HitCountMixin):
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    tags = models.ManyToManyField(Tag, blank=False, related_name='tag')
    slug = models.SlugField(default='', editable=False, max_length=200, null=False, unique=True)
    body = models.TextField()
    excerpt = models.TextField(max_length=500, blank=True)
    show_excerpt_in_article = models.BooleanField(default=True)
    date = models.DateField(default=datetime.now)
    time = models.TimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    thumb = models.ImageField(blank=True, upload_to='article/article_thumbs')
    thumb_alt = models.CharField(max_length=50, default='', blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'
    
    def get_datetime(self):
        return datetime.combine(self.date, self.time)

    def get_absolute_url(self):
        kwargs = {
            'pk': self.id,
            'slug': self.slug
        }
        return reverse('article-detail', kwargs=kwargs)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title + '--' +
                                get_random_string(length=7))
        super(Article, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-date']



class Comment(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, blank=True, null=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='article')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-datetime']


# article request submition model
class ArticleSubmission(models.Model):
    # converting filename into random string
    def get_hashed_file_path(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (uuid.uuid4(), ext)
        return os.path.join('article/submissions/documents/', filename)
    
    status_choices = (
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    )

    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, blank=True, null=True)
    as_anonymous = models.BooleanField(default=False)
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField(blank=True)
    summary = models.TextField(max_length=500, blank=True)
    additional_info = models.TextField(max_length=500, blank=True)
    thumb = models.ImageField(upload_to='article/submissions/submission_thumbs', blank=True)
    thumb_alt = models.CharField(max_length=50, default='', blank=True)
    datetime = models.DateTimeField(auto_now=True)
    documents = models.FileField(upload_to=get_hashed_file_path, validators=[validate_file_size], blank=False)
    status = models.CharField(choices=status_choices, max_length=50, default='pending')
    
    def __str__(self):
        return self.title
    
    def delete(self, *args, **kwargs):
        if self.documents:
            self.documents.delete()
            super().delete(*args, **kwargs)

    class Meta:
        ordering = ['-datetime']

article/forms.py
from django.forms import ModelForm, ClearableFileInput
from django.utils.translation import gettext_lazy as _

from .models import ArticleSubmission

class ArticleSubmissionForm(ModelForm):
    class Meta:
        model = ArticleSubmission
        exclude = ['user', 'body', 'status']
        field_requireds = {
            'title': _('Title is required.'),
            'email': _('Email is required for validation purpose.'),
            'documents': _('At least 1 document is required.'),
        }
        labels = {
            'as_anonymous': _('Submit Anonymously'),
            'documents': _('Upload Document'),
        }

article/views.py
from unicodedata import category
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.messages.views import SuccessMessageMixin
from hitcount.views import HitCountDetailView
from django.urls import reverse_lazy

from django.contrib.auth.models import User
from .forms import ArticleSubmissionForm
from .models import Article, Comment, ArticleSubmission


class ArticleDetailView(HitCountDetailView):
    model = Article
    template_name = 'article/single-standard.html'
    context_object_name = 'article'
    count_hit = True
    
    def get_previous_article(self):
        article_id = self.get_object().id
        if article_id > 1:
            previous_article = Article.objects.get(id=article_id-1,category=self.model.category)
        else:
            previous_article = Article.objects.get(id=1,category=self.model.category)
        
        return previous_article
    
    def get_next_article(self):
        article_id = self.get_object().id
        if article_id < Article.objects.count():
            next_article = Article.objects.get(id=article_id + 1,category=self.model.category)
        else:
            next_article = Article.objects.get(id=Article.objects.count(),category=self.model.category)
        
        return next_article
    
    
    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(article=self.get_object())
        context['previous_article'] = self.get_previous_article()
        context['next_article'] = self.get_next_article()
        return context
        

class SearchArticlesListView(ListView):
    model = Article
    template_name = 'article/search-articles.html'
    paginate_by = 10
    context_object_name = 'articles'
    
    def get_queryset(self):
        articles = super(SearchArticlesListView, self).get_queryset()
        query = self.kwargs.get('query', None)
        articles = Article.objects.filter(title__icontains=query)

        sort_by = self.request.GET.get('sort_by', '')
        date_from = self.request.GET.get('date_from', '')
        date_to = self.request.GET.get('date_to', '')

        if sort_by == 'popular':
            articles = articles.order_by('-hit_count_generic__hits')
        elif sort_by == 'newest':
            articles = articles.order_by('-date')
        elif sort_by == 'oldest':
            articles = articles.order_by('date')
        
        if date_from and date_to:
            articles = articles.filter(date__range=(date_from, date_to))
        
        return articles
    
    def get_context_data(self, **kwargs):
        context = super(SearchArticlesListView, self).get_context_data(**kwargs)
        context['query'] = self.kwargs.get('query', None)
        context['filters'] = {
            'sort_by': self.request.GET.get('sort_by', ''),
            'date_from': self.request.GET.get('date_from', ''),
            'date_to': self.request.GET.get('date_to', ''),
        }
        return context

class ArticleSubmissionView(SuccessMessageMixin, CreateView):
    model = ArticleSubmission
    form_class = ArticleSubmissionForm
    template_name = 'article/submit-article.html'
    context_object_name = 'article'
    success_url = reverse_lazy('article:submit-success')
    success_message = 'Your article request has been submitted successfully. Expect a response within 48 hrs.'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid() and request.user.is_authenticated:
            form.instance.user = User.objects.get(username=request.user)
            form.instance.save()
            return self.form_valid(form)
        else:
            return self.form_valid(form)


class BlogView(ListView):
    model = Article
    template_name = 'article/blog.html'
    context_object_name = 'articles'

    def get_queryset(self):
        articles = super(BlogView, self).get_queryset()
        articles = articles.filter(tags__name='blog').order_by('-date')
        return articles

def article_submission_success(request):
    return render(request, 'article/submit-success.html')

def blog(request):
    return render(request, 'article/blog.html')
def blog_detail(request, blog):
    return render(request, 'article/blog-post.html')

article/templates/article/single-standard.html
{% extends 'home/base.html' %}
{% load markdownify %}
{% load account_tags %}

{% block meta %}
{% include 'home/components/~common/meta.html' with meta_title=article.title meta_desc=article.body|striptags|truncatechars:150 %}
{% endblock meta %}

{% block title %}
{{ article.title }} | by {{article.author.userprofile.get_full_name}} | Neutral Tip
{% endblock title %}

{% block body %}
   <!-- content
   ================================================== -->
   <section id="content-wrap" class="blog-single">
   	<div class="row">
   		<div class="col-twelve">

   			<article class="format-standard">  
				
				{% if article.thumb %}
				<div class="content-media">
					<div class="post-thumb">
						<img src="{{article.thumb.url}}" alt="{{article.thumb_alt}}" style="max-height: 20em;">
					</div>
				</div>
				{% endif %}

				<div class="primary-content">

					<h1 class="page-title">{{article.title}}</h1>	

					<ul class="entry-meta">
						{% user_name article.author href=True %}
						- <li class="date">{{article.get_datetime |date:"F j, Y, g:i a"}}</li>
						<br>
						<li class="cat">
							Category: <a href="{% url 'home:category_page' category=article.category %}">{{article.category |capfirst}}</a>
						</li>
					</ul>

					<div class="entry-excerpt">
						{% if article.show_excerpt_in_article %}
						<p class="lead">{{article.excerpt}}</p>
						{% endif %}
					</div>

					{{article.body | markdownify}}

					<p class="tags">
						<span>Tagged in :</span>
						{% for tag in article.tags.all %}
						<a href="{% url 'home:tag_page' tag=tag %}">{{tag}}</a>
						{% endfor %}
					</p>

					{% with article.author.userprofile as author %}
						{% if author.display_profile %}
						<div class="author-profile">
							{% profile_pic article.author %}

							<div class="about">
								<h4>{% user_name article.author href=True with_username=True %}</h4>

								{% if author.display_bio %}
								<p>{{author.bio}}</p>
								{% endif %}

								{% if author.display_socials %}
								<ul class="author-social">
									{% if author.facebook %}
									<li><a target="_blank" href="https://facebook.com/{{author.facebook}}">Facebook</a></li>
									{% endif %}
									{% if author.twitter %}
									<li><a target="_blank" href="https://twitter.com/{{author.twitter}}">Twitter</a></li>
									{% endif %}
									{% if author.instagram %}
									<li><a target="_blank" href="https://instagram.com/{{author.instagram}}">Instagram</i></a></li>					        	
									{% endif %}
									{% if author.website %}
									<li><a target="_blank" href="{{author.website}}">Website</a></li>
									{% endif %}
								</ul>
								{% endif %}
							</div>
						</div> <!-- end author-profile -->						
						{% endif %}
					{% endwith %}

				</div> <!-- end entry-primary -->		  			   

				<div class="pagenav group">
					<div class="prev-nav">
					<a href="{% url 'article:detail' slug=previous_article.slug %}" rel="prev">
						<span>Previous</span>
						{{previous_article.title}}
					</a>
					</div>
					<div class="next-nav">
						<a href="{% url 'article:detail' slug=next_article.slug %}" rel="next">
							<span>Next</span>
							{{next_article.title}}
						</a>
					</div>  				   
				</div>

			</article>
	

		</div> <!-- end col-twelve -->
   	</div> <!-- end row -->

		<div class="comments-wrap">
			<div id="comments" class="row">
				<div class="col-full">

               <h3>{{ comments|length }} Comment{{ comments|length|pluralize }} </h3>

               <!-- commentlist -->
               	<ol class="commentlist">
					{% for comment in comments %}
					<li class="depth-1">

						<div class="avatar">
						{% if comment.user %}
							{% profile_pic comment.user %}
						{% else %}
							<svg data-jdenticon-value="{{ comment.email }}" title="this image is unique for your Email ID"></svg>
						{% endif %}
						</div>

						<div class="comment-content">

							<div class="comment-info">
								<cite>{{ comment.name }}</cite>

								<div class="comment-meta">
								<time class="comment-time" datetime="2014-07-12T23:05">{{ comment.datetime |date:"F j, Y @ g:i a"}} </time>
								</div>
							</div>

							<div class="comment-text">
								<p>{{ comment.body }}</p>
							</div>

						</div>

					</li>
					{% endfor %}

               	</ol> <!-- Commentlist End -->					

               <!-- respond -->
               <div class="respond">

               	<h3>Leave a Comment</h3>

                  <form name="contactForm" id="contactForm" method="post" action="">
  					   <fieldset>

                     <div class="form-field">
  						      <input name="cName" type="text" id="cName" class="full-width" placeholder="Your Name" value="">
                     </div>

                     <div class="form-field">
  						      <input name="cEmail" type="text" id="cEmail" class="full-width" placeholder="Your Email" value="">
                     </div>

                     <div class="form-field">
  						      <input name="cWebsite" type="text" id="cWebsite" class="full-width" placeholder="Website"  value="">
                     </div>

                     <div class="message form-field">
                        <textarea name="cMessage" id="cMessage" class="full-width" placeholder="Your Message" ></textarea>
                     </div>

                     <button type="submit" class="submit button-primary">Submit</button>

  					   </fieldset>
  				      </form> <!-- Form End -->

               </div> <!-- Respond End -->

         	</div> <!-- end col-full -->
         </div> <!-- end row comments -->
		</div> <!-- end comments-wrap -->

   </section> <!-- end content -->

{% endblock body %}

article/templates/article/submit-article.html
{% extends 'home/base.html' %}
{% load account_tags %}

{% block title %}Submit: Article | Neutral Tip{% endblock title %}

{% block css %}
.alert .danger {
    color: red
}
input, textarea {
    width: 100%;
}
form [type=checkbox] {
    width: 20px;
    height: 20px;
}
textarea:focus, input:focus {
    background-color: #dcdcdc !important;
    caret-color: #000000;
    color: #000000;
}

.toolbar {
    background-color: #f5f5f5;
    border-bottom: 1px solid #ccc;
    padding: 10px;
}
.toolbar a {
    background-color: #f5f5f5;
    border: 1px solid #ccc;
    padding: 5px;
    margin-left: 5px;
    margin-right: 5px;
    font-size: 20px;
    color: #000;
    text-decoration: none;
}
.toolbar .divider::after {
    margin-left: 10px;
    margin-right: 10px;
    font-size: 20px;
    color: #747474;
    content: '|';
}
{% endblock css %}

{% block body %}

<section id="content-wrap">
    <div class="row">
        
        <div class="alert">
            <div class="danger">
                {{form.errors.documents.0}}
            </div>
        </div>

        <br />
        
        <div class="col-twelve">
            <form action="{% url 'article:submit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            {% if request.user.is_authenticated %}
                {% user_name user href=True as user_name %}
                <h3> Currently logged in as: {{user_name}}</h3>
            {% else %}
                <h3> Anonymous Identity </h3>
            {% endif %}
            <mark> Classic/Visual text editor is not available for this moment <br/>
             you may upload Word&lpar;.docx&rpar;/PDF&lpar;.pdf&rpar; or other document formats to request a publish</mark>
             <br />
             <br />
             <br />

            {% for element in form %}
                <div class="form-group">
                    <label for="title">{{element.label}}</label>
                    {% if element.name == 'body' %}

                        <div class="toolbar">
                            <a title="Bold"><i class="fa fa-bold"></i></a>
                            <a title="Italic"><i class="fa fa-italic"></i></a>
                            <a title="Underline"><i class="fa fa-underline"></i></a>
                            <a title="Strikethrough"><i class="fa fa-strikethrough"></i></a>
                            <span class="divider"></span>
                            <a title="Unordered List"><i class="fa fa-list-ul"></i></a>
                            <a title="Ordered List"><i class="fa fa-list-ol"></i></a>
                            <a title="Blockquote"><i class="fa fa-quote-right"></i></a>
                            <span class="divider"></span>
                            <a title="Code Block"><i class="fa fa-code"></i></a>
                            <a title="Inline Code"><i class="fa fa-code-fork"></i></a>
                            <span class="divider"></span>
                            <a title="Link"><i class="fa fa-link"></i></a>
                            <a title="Unlink"><i class="fa fa-unlink"></i></a>
                            <a title="Clear formatting"><i class="fa fa-eraser"></i></a>
                        </div>
                        </div>

                    {% endif %}
                    {{element}}
                </div>
            {% endfor %}

            <mark>You can zip the many files into one .zip file if you please to upload more than one document</mark>
            <br />
            <br />
            
            <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</section>

{% endblock body %}