account/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'
urlpatterns = [
    path('sign-up/', views.sign_up, name='signup'),
    path('sign-in/', auth_views.LoginView.as_view(template_name='account/sign-in.html'), name='signin'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit/', views.UserProfileEditView.as_view(), name='user_profile_edit'),
    path('<str:user>/', views.user_profile, name='user_profile'),
]

home/urls.py
from django.urls import path

from django.views.generic import TemplateView
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.ArticleListView.as_view(), name='index'),
    path('category/', views.category_all, name='category_all'),
    path('category/<str:category>/', views.CategoryListView.as_view(), name='category_page'),
    path('tag/<str:tag>/', views.TagListView.as_view(), name='tag_page'),
    path('about/', TemplateView.as_view(template_name='home/about.html'), name='about'),
    path('contact/', TemplateView.as_view(template_name='home/contact.html'), name='contact'),
    path('support/', TemplateView.as_view(template_name='home/support.html'), name='support'),
    path('credits/', TemplateView.as_view(template_name='home/credits.html'), name='credits'),
    path('faqs/', views.FaqListView.as_view(), name='faqs'),
    path('privacy-policy/', TemplateView.as_view(template_name='home/privacy-policy.html'), name='privacy_policy'),
    path('terms/', TemplateView.as_view(template_name='home/terms.html'), name='terms'),
]

home/templates/home/components/~common/footer.html
<footer>
  <div class="footer-main">
    <div class="row">
      <div class="col-four tab-full mob-full footer-info">
        <h4>About Our Site</h4>

        <p>
          Neutral Tip is an Indian non-profit organization that publishes news, disclosures, 
          classified media provided by sources, media critique, reportage and satirical views 
          on current happenings around. It was founded in 2021 under the holding company MRVAIBH Inc.
        </p>
      </div>
      <!-- end footer-info -->

      <div class="col-two tab-1-3 mob-1-2 site-links">
        <h4>Site Links</h4>

        <ul>
          <li><a href="{% url 'home:about' %}">About Us</a></li>
          <li><a href="{% url 'article:blog' %}">Blog</a></li>
          <li><a href="{% url 'home:faqs' %}">FAQ</a></li>
          <li><a href="{% url 'home:terms' %}">Terms</a></li>
          <li><a href="{% url 'home:privacy_policy' %}">Privacy Policy</a></li>
        </ul>
      </div>
      <!-- end site-links -->

      <div class="col-two tab-1-3 mob-1-2 social-links">
        <h4>Social</h4>

        <ul>
          <li><a href="https://twitter.com/MrVaiBH0" target="_blank">Twitter</a></li>
          <li><a href="https://facebook.com/MrVaiBH0" target="_blank">Facebook</a></li>
          <li><a href="https://instagram.com/mrvaibh0/" target="_blank">Instagram</a></li>
        </ul>
      </div>
      <!-- end social links -->

      <div class="col-four tab-1-3 mob-full footer-subscribe">
        <h4>Subscribe</h4>

        <p>Keep yourself updated. Subscribe to our newsletter.</p>

        <div class="subscribe-form">
          <form id="mc-form" class="group" novalidate="true">
            <input
              type="email"
              value=""
              name="dEmail"
              class="email"
              id="mc-email"
              placeholder="Type &amp; press enter"
              required=""
            />

            <input type="submit" name="subscribe" />

            <label for="mc-email" class="subscribe-message"></label>
          </form>
        </div>
      </div>
      <!-- end subscribe -->
    </div>
    <!-- end row -->
  </div>
  <!-- end footer-main -->

  <div class="footer-bottom">
    <div class="row">
      <div class="col-twelve">
        <div class="copyright">
          <span>&copy; Neutral Tip Pvt. Ltd. 2021</span>
          <span
            >Template theme credit -
            <a href="http://www.styleshout.com/" target="_blank">styleshout</a>
             (Abstract)
          </span>
        </div>

        <div id="go-top">
          <a class="smoothscroll" title="Back to Top" href="#top">
            <i class="icon icon-arrow-up"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</footer>

home/templates/home/components/~common/navbar.html
<header class="short-header">
  <div class="gradient-block"></div>

  <div class="row header-content">
    <div class="logo" onclick="window.location='/'">
      <img href="{% url 'home:index' %}" />
      <span> | NEUTRAL TIP</span>
    </div>

    {% with request.path as current_url %}
    <nav id="main-nav-wrap">
      <ul class="main-navigation sf-menu">
        <li class="{% if current_url == "/" %}current{% endif %}">
          <a href="{% url 'home:index' %}" title="">Home</a>
        </li>
        <li class="has-children {% if "category" in current_url %}current{% endif %}">
          <a href="{% url 'home:category_all' %}" title="">Categories</a>
          <ul class="sub-menu">
            {% for category in categories %}
            <li><a href="{% url 'home:category_page' category=category.name %}">{{category.name |capfirst}}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li class="{% if "blog" in current_url %}current{% endif %}">
          <a href="{% url 'article:blog' %}" title="">Blog</a>
        </li>
        <li class="{% if "about" in current_url %}current{% endif %}">
          <a href="{% url 'home:about' %}" title="">About</a>
        </li>
        <li class="{% if "contact" in current_url %}current{% endif %}">
          <a href="{% url 'home:contact' %}" title="">Contact</a>
        </li>
        <li class="{% if "support" in current_url %}current{% endif %}">
          <a href="{% url 'home:support' %}" title="">Support</a>
        </li>
        <li class="{% if "credits" in current_url %}current{% endif %}">
          <a href="{% url 'home:credits' %}" title="">Credits</a>
        </li>
        <li class="{% if "faq" in current_url %}current{% endif %}">
          <a href="{% url 'home:faqs' %}" title="">FAQ</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="has-children {% if "myprofile" in current_url %}current{% endif %}">
          <a href="#" title="">Me</a>
          <ul class="sub-menu">
            <li><a href="{% url 'account:user_profile' user=request.user %}">Profile</a></li>
            <hr>
            <li><a href="{% url 'account:logout' %}">Logout</a></li>
          </ul>
        </li>
        {% else %}
        <li class="{% if "sign-in" in current_url %}current{% endif %}">
          <a href="{% url 'account:signin' %}" title="">Login</a>
        </li>
        <li class="{% if "sign-up" in current_url %}current{% endif %}">
          <a href="{% url 'account:signup' %}" title="">Register</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endwith %}
    <!-- end main-nav-wrap -->

    <div class="search-wrap">
      <form class="search-form" id="search-form">
        <label>
          <span class="hide-content">Search for:</span>
          <input
            type="search"
            class="search-field"
            id="search-field"
            placeholder="Type Your Keywords"
            value=""
            name="s"
            title="Search for:"
            autocomplete="off"
          />
        </label>
        <input type="submit" class="search-submit" value="Search" />
      </form>

      <a href="#" id="close-search" class="close-btn">Close</a>
    </div>
    <!-- end search wrap -->

    <div class="triggers">
      <a class="search-trigger" href="#"><i class="fa fa-search"></i></a>
      <a class="menu-toggle" href="#"><span>Menu</span></a>
    </div>
    <!-- end triggers -->
  </div>
</header>