home/urls.py
from django.urls import path

from django.views.generic import TemplateView
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.ArticleListView.as_view(), name='index'),
    path('category/', views.category_all, name='category_all'),
    path('category/<str:category>/', views.CategoryListView.as_view(), name='category_page'),
    path('tag/<str:tag>/', views.TagListView.as_view(), name='tag_page'),
    path('about/', TemplateView.as_view(template_name='home/about.html'), name='about'),
    path('contact/', TemplateView.as_view(template_name='home/contact.html'), name='contact'),
    path('support/', TemplateView.as_view(template_name='home/support.html'), name='support'),
    path('credits/', TemplateView.as_view(template_name='home/credits.html'), name='credits'),
    path('faqs/', views.FaqListView.as_view(), name='faqs'),
    path('privacy-policy/', TemplateView.as_view(template_name='home/privacy-policy.html'), name='privacy_policy'),
    path('terms/', TemplateView.as_view(template_name='home/terms.html'), name='terms'),
]

neutraltip/urls.py
from django.contrib import admin
from django.urls import path, include

# For STATIC & MEDIA files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin_panel'),
    path('', include('home.urls', namespace='home')),
    path('', include('article.urls', namespace='article')),
    path('account/', include('account.urls', namespace='account')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/templates/home/components/Home/general-card.html
{% load account_tags %}

<article class="brick entry format-standard animate-this">
  {% if article.thumb %}
  <div class="entry-thumb">
    <a href="single-standard.html" class="thumb-link">
      <img src="{{article.thumb.url}}" alt="{{article.thumb_alt}}" />
    </a>
  </div>
  {% endif %}

  <div class="entry-text">
    <div class="entry-header">
      <div class="entry-meta">
        <span class="cat-links">
          {% for tag in article.tags.all %}
          <a href="{% url 'article:tag_page' tag=tag %}">{{tag}}</a>
          {% endfor %}
        </span>
      </div>

      <h1 class="entry-title">
        <a href="{% url 'article:detail' slug=article.slug %}">{{article.title}}</a>
      </h1>
    </div>

    <div class="entry-excerpt">
    {% if article.show_excerpt %}
      {{article.excerpt}}
    {% else %}
      {{article.body|striptags|truncatechars:255}}
    {% endif %}
    </div>

    <ul class="entry-meta">
      <span class="cat-links">
        {{article.get_datetime |date:"F j, Y, g:i a"}}
          {% user_name article.author href=True %}
      </span>
    </ul>
  </div>
</article>